_target_: navsim.agents.pad.pad_agent.PadAgent
_convert_: 'all'

config:
  _target_: navsim.agents.pad.navsim_config.PadConfig
  _convert_: 'all'

  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5

  latent: False

checkpoint_path: '/home/users/ntu/lyuchen/scratch/keguo_projects/ntu/exp/ke/pad_mlp3_area2/03.24_14.00/lightning_logs/version_0/checkpoints/epoch=12-step=8632.ckpt'
lr: 1e-4
