_target_: navsim.agents.pad.pad_agent.PadAgent
_convert_: 'all'

config:
  _target_: navsim.agents.pad.pad_config.PadConfig
  _convert_: 'all'

  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5

  latent: False

checkpoint_path: '/home/ke/PAD/exp/navsimepoch=25-step=8632.ckpt'
lr: 1e-4
